CREATE TABLE IF NOT EXISTS audit_logs (
  audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor_id UUID REFERENCES users(user_id) ON DELETE SET NULL,
  actor_role user_role,
  action VARCHAR(40) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id VARCHAR(64) NOT NULL,
  before JSONB,
  after JSONB,
  ip_address INET,
  user_agent TEXT,
  PRIMARY KEY (audit_id, occurred_at)
) PARTITION BY RANGE (occurred_at);

CREATE TABLE IF NOT EXISTS audit_logs_default PARTITION OF audit_logs DEFAULT;

REVOKE UPDATE, DELETE ON audit_logs FROM PUBLIC;
